# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/infrastructure/task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/infrastructure/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/infrastructure/task.proto\x12\x04task\"\x07\n\x05\x45mpty\"\x88\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10\x63onfiguration_id\x18\x02 \x01(\t\x12\x13\n\x0blocation_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x0f\n\x07role_id\x18\x05 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x06 \x01(\x03\x12\x11\n\tcompleted\x18\x07 \x01(\x08\"v\n\x11\x43reateTaskRequest\x12\x18\n\x10\x63onfiguration_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07role_id\x18\x04 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x05 \x01(\x03\"&\n\x13\x43ompleteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"$\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"!\n\x0eGetTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"1\n\x12GetAllTasksRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"0\n\x13GetAllTasksResponse\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task2\x9c\x02\n\x0bTaskService\x12\x31\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\n.task.Task\x12\x35\n\x0c\x43ompleteTask\x12\x19.task.CompleteTaskRequest\x1a\n.task.Task\x12\x32\n\nDeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x0b.task.Empty\x12+\n\x07GetTask\x12\x14.task.GetTaskRequest\x1a\n.task.Task\x12\x42\n\x0bGetAllTasks\x12\x18.task.GetAllTasksRequest\x1a\x19.task.GetAllTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.infrastructure.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_TASK']._serialized_start=49
  _globals['_TASK']._serialized_end=185
  _globals['_CREATETASKREQUEST']._serialized_start=187
  _globals['_CREATETASKREQUEST']._serialized_end=305
  _globals['_COMPLETETASKREQUEST']._serialized_start=307
  _globals['_COMPLETETASKREQUEST']._serialized_end=345
  _globals['_DELETETASKREQUEST']._serialized_start=347
  _globals['_DELETETASKREQUEST']._serialized_end=383
  _globals['_GETTASKREQUEST']._serialized_start=385
  _globals['_GETTASKREQUEST']._serialized_end=418
  _globals['_GETALLTASKSREQUEST']._serialized_start=420
  _globals['_GETALLTASKSREQUEST']._serialized_end=469
  _globals['_GETALLTASKSRESPONSE']._serialized_start=471
  _globals['_GETALLTASKSRESPONSE']._serialized_end=519
  _globals['_TASKSERVICE']._serialized_start=522
  _globals['_TASKSERVICE']._serialized_end=806
# @@protoc_insertion_point(module_scope)
