
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "50051:50051"
    environment:
      - LOG_LEVEL=INFO
      - REPOSITORY_TYPE=mongo
      - EVENT_SENDER_TYPE=nats
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
