# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.infrastructure.api import task_pb2 as src_dot_infrastructure_dot_api_dot_task__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/infrastructure/api/task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/task.TaskService/CreateTask',
                request_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/task.TaskService/CompleteTask',
                request_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/task.TaskService/DeleteTask',
                request_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/task.TaskService/GetTask',
                request_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.GetAllTasks = channel.unary_unary(
                '/task.TaskService/GetAllTasks',
                request_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksRequest.SerializeToString,
                response_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.CreateTaskRequest.FromString,
                    response_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.CompleteTaskRequest.FromString,
                    response_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.DeleteTaskRequest.FromString,
                    response_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.Empty.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetTaskRequest.FromString,
                    response_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.Task.SerializeToString,
            ),
            'GetAllTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTasks,
                    request_deserializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksRequest.FromString,
                    response_serializer=src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('task.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/CreateTask',
            src_dot_infrastructure_dot_api_dot_task__pb2.CreateTaskRequest.SerializeToString,
            src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/CompleteTask',
            src_dot_infrastructure_dot_api_dot_task__pb2.CompleteTaskRequest.SerializeToString,
            src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/DeleteTask',
            src_dot_infrastructure_dot_api_dot_task__pb2.DeleteTaskRequest.SerializeToString,
            src_dot_infrastructure_dot_api_dot_task__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/GetTask',
            src_dot_infrastructure_dot_api_dot_task__pb2.GetTaskRequest.SerializeToString,
            src_dot_infrastructure_dot_api_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/GetAllTasks',
            src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksRequest.SerializeToString,
            src_dot_infrastructure_dot_api_dot_task__pb2.GetAllTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
